"use client"

export type ResourceCategory =
  | "Purpose" | "Vision" | "Goals" | "Habits" | "Tasks" | "Journal"
  | "Mindfulness" | "Health" | "Learning" | "Productivity" | "Leadership"
  | "Finance" | "Relationships" | "Faith" | "Personal Growth"

export type ResourceType = "article" | "guide" | "exercise" | "worksheet" | "template" | "prompt" | "book" | "video" | "podcast" | "checklist" | "framework"

export type DifficultyLevel = "beginner" | "intermediate" | "advanced"

export interface Resource {
  id: string
  title: string
  description: string
  category: ResourceCategory
  type: ResourceType
  difficulty: DifficultyLevel
  content: string
  tags: string[]
  trackerId?: string
  readTime?: string
}

export const RESOURCE_CATEGORIES: { id: ResourceCategory; label: string; icon: string; description: string }[] = [
  { id: "Purpose", label: "Purpose", icon: "🎯", description: "Discover your meaning and mission" },
  { id: "Vision", label: "Vision", icon: "🔮", description: "Create a compelling future" },
  { id: "Goals", label: "Goals", icon: "🏆", description: "Set and achieve meaningful goals" },
  { id: "Habits", label: "Habits", icon: "🔄", description: "Build lasting positive routines" },
  { id: "Tasks", label: "Tasks", icon: "✅", description: "Execute with focus and clarity" },
  { id: "Journal", label: "Journal", icon: "📖", description: "Reflect and grow through writing" },
  { id: "Mindfulness", label: "Mindfulness", icon: "🧘", description: "Find peace and presence" },
  { id: "Health", label: "Health", icon: "💪", description: "Nourish your body and mind" },
  { id: "Learning", label: "Learning", icon: "📚", description: "Expand your knowledge" },
  { id: "Productivity", label: "Productivity", icon: "⚡", description: "Accomplish more with intention" },
  { id: "Leadership", label: "Leadership", icon: "👑", description: "Lead with purpose and influence" },
  { id: "Finance", label: "Finance", icon: "💰", description: "Build wealth with wisdom" },
  { id: "Relationships", label: "Relationships", icon: "❤️", description: "Deepen connection and trust" },
  { id: "Faith", label: "Faith", icon: "🙏", description: "Grow spiritually and stay grounded" },
  { id: "Personal Growth", label: "Personal Growth", icon: "🌱", description: "Become your best self" },
]

export const RESOURCE_TYPES: { id: ResourceType; label: string; icon: string }[] = [
  { id: "article", label: "Articles", icon: "📄" },
  { id: "guide", label: "Guides", icon: "📘" },
  { id: "exercise", label: "Exercises", icon: "🎯" },
  { id: "worksheet", label: "Worksheets", icon: "📝" },
  { id: "template", label: "Templates", icon: "📋" },
  { id: "prompt", label: "Reflection Prompts", icon: "💭" },
  { id: "book", label: "Book Recommendations", icon: "📕" },
  { id: "video", label: "Videos", icon: "🎬" },
  { id: "podcast", label: "Podcasts", icon: "🎧" },
  { id: "checklist", label: "Checklists", icon: "☑️" },
  { id: "framework", label: "Frameworks", icon: "🏗️" },
]

export const TRACKER_RESOURCE_MAP: Record<string, ResourceCategory[]> = {
  mood: ["Personal Growth", "Mindfulness", "Journal"],
  period: ["Health"],
  weight: ["Health", "Habits"],
  exercise: ["Health", "Habits", "Productivity"],
  lifestyle: ["Habits", "Health", "Productivity"],
  finance: ["Finance", "Goals"],
  content: ["Productivity", "Learning"],
  student: ["Learning", "Productivity", "Tasks"],
  business: ["Leadership", "Finance", "Goals"],
  mindfulness: ["Mindfulness", "Faith", "Personal Growth"],
  custom: ["Personal Growth"],
}

export const ALL_RESOURCES: Resource[] = [
  // ─── PURPOSE ───
  { id: "purpose-1", title: "Discovering Your Life Purpose", description: "A step-by-step guide to uncovering the deeper meaning behind your existence and aligning your daily actions with your core mission.", category: "Purpose", type: "guide", difficulty: "beginner", content: "Your purpose is the intersection of what you love, what you are good at, what the world needs, and what you can be rewarded for. Start by reflecting on these four areas:\n\n1. **Passion**: What activities make you lose track of time?\n2. **Skill**: What do others come to you for help with?\n3. **Need**: What problem in the world breaks your heart?\n4. **Value**: What can you offer that others would invest in?\n\nWrite your answers down. Look for the overlap. That intersection is where your purpose begins to take shape.\n\n**Exercise**: Write a Purpose Statement in one sentence: 'I use my [skill] to [action] for [audience] so that [impact].'", tags: ["purpose", "meaning", "self-discovery"], readTime: "8 min" },
  { id: "purpose-2", title: "Values Clarification Exercise", description: "Identify and prioritize the core values that guide your decisions, relationships, and life direction.", category: "Purpose", type: "exercise", difficulty: "beginner", content: "Your values are your internal compass. When you live aligned with your values, you feel authentic and fulfilled. When you do not, you feel restless and conflicted.\n\n**Step 1**: From the list below, select your top 10 values:\nIntegrity, Freedom, Family, Growth, creativity, Adventure, Service, Faith, Knowledge, Health, Wealth, Love, Justice, Simplicity, Courage, Humility, Excellence, Gratitude, Patience, Connection\n\n**Step 2**: Narrow to your top 5.\n\n**Step 3**: For each value, write one sentence about why it matters to you.\n\n**Step 4**: Rank them 1-5. When two values conflict, which one wins?\n\nThese are your non-negotiable values. Use them as a filter for every major decision.", tags: ["values", "purpose", "identity"], readTime: "15 min" },
  { id: "purpose-3", title: "Life Mission Worksheet", description: "A structured worksheet to craft your personal life mission statement that guides all your goals and decisions.", category: "Purpose", type: "worksheet", difficulty: "intermediate", content: "**Life Mission Worksheet**\n\n**Part 1: Reflection**\n- What moments in your life have felt most meaningful?\n- When have you felt most alive and aligned?\n- What would you do if money were no object?\n- What legacy do you want to leave?\n\n**Part 2: Drafting**\nComplete these sentences:\n- I am at my best when I...\n- The impact I want to have is...\n- The people I want to serve are...\n- The change I want to see in the world is...\n\n**Part 3: Synthesis**\nCombine your answers into a 1-2 sentence mission statement. Revise it until it feels true.\n\n**Example**: 'To inspire and equip young leaders to discover their purpose and build lives of meaning, impact, and faith.'", tags: ["purpose", "mission", "planning"], readTime: "20 min" },

  // ─── VISION ───
  { id: "vision-1", title: "Creating a Compelling Life Vision", description: "Learn how to craft a vivid, emotionally resonant picture of your ideal future across every area of life.", category: "Vision", type: "guide", difficulty: "beginner", content: "A life vision is a detailed picture of your ideal future. It is not a goal list; it is a narrative of who you are becoming.\n\n**The Vision Framework**:\nWrite a paragraph for each area of your life as if it is 5 years from now and everything has gone perfectly:\n\n1. **Health & Energy**: How do you feel? What does your body look like?\n2. **Relationships**: Who is around you? How do they describe you?\n3. **Career & Purpose**: What are you building? What is your impact?\n4. **Finances**: What is your financial position? What freedom do you have?\n5. **Personal Growth**: What have you learned? Who have you become?\n6. **Faith & Spirituality**: What is your spiritual life like?\n7. **Fun & Adventure**: What experiences have you had?\n\nRead your vision daily. Let it shape your goals.", tags: ["vision", "future", "planning"], readTime: "12 min" },
  { id: "vision-2", title: "Vision Board Creation Guide", description: "A practical guide to creating a visual vision board that keeps your future front and center in your daily life.", category: "Vision", type: "guide", difficulty: "beginner", content: "A vision board is a visual representation of your goals and dreams. It serves as a daily reminder of what you are working toward.\n\n**How to Create Your Vision Board**:\n\n1. **Gather images** that represent your ideal life (magazines, Pinterest, screenshots)\n2. **Choose a board** (physical corkboard or digital like Canva)\n3. **Organize by life area**: Health, Career, Relationships, Faith, Finance, Growth\n4. **Add words** that reinforce your values and identity\n5. **Place it** where you will see it every morning and evening\n\n**Pro Tip**: The most effective vision boards are reviewed daily, not just created once. Spend 2 minutes each morning visualizing yourself already living this vision.", tags: ["vision", "visualization", "goals"], readTime: "10 min" },
  { id: "vision-3", title: "Future Self Exercise", description: "A powerful journaling exercise to connect with your future self and bridge the gap between who you are and who you are becoming.", category: "Vision", type: "exercise", difficulty: "intermediate", content: "**Future Self Journaling Exercise**\n\nSet a timer for 15 minutes. Write a letter FROM your future self (5 years from now) TO your current self.\n\nYour future self should:\n- Describe a typical day in their life\n- Share what they are most proud of\n- Explain what habits got them there\n- Warn about the pitfalls to avoid\n- Offer encouragement for the hard days\n\n**Prompt starters**:\n- 'Dear [name], I am writing to you from [year]. I want you to know that...'\n- 'The thing you are most worried about right now...'\n- 'The habit that changed everything was...'\n- 'I wish you knew that...'\n\n**After writing**: Read it aloud. What is one thing your future self wants you to start doing today?", tags: ["vision", "journaling", "self-discovery"], readTime: "15 min" },

  // ─── GOALS ───
  { id: "goals-1", title: "Milestone Planning: From Big Dream to Action Steps", description: "Learn how to break any ambitious goal into manageable milestones that create momentum and maintain motivation.", category: "Goals", type: "guide", difficulty: "beginner", content: "Big goals feel overwhelming. Milestones make them achievable.\n\n**The Milestone Method**:\n\n1. **Define the Goal**: Write it in one sentence with a deadline\n2. **Work Backward**: Ask 'What needs to be true 1 month before completion?' Then 'What needs to be true 1 month before that?'\n3. **Create 3-5 Milestones**: Each milestone is a significant checkpoint\n4. **Break Milestones into Projects**: Each project is a 1-4 week effort\n5. **Break Projects into Tasks**: Each task is a 1-3 day action\n\n**Example**:\n- Goal: Launch online course by December\n- Milestone 1 (Sep): Course content complete\n- Milestone 2 (Oct): Sales page live\n- Milestone 3 (Nov): Beta test done\n- Project: Record Module 1\n- Task: Write outline for Lesson 1", tags: ["goals", "planning", "milestones"], readTime: "10 min" },
  { id: "goals-2", title: "SMART vs Outcome Goals", description: "Understand the difference between process goals and outcome goals, and when to use each approach.", category: "Goals", type: "article", difficulty: "intermediate", content: "**Outcome Goals vs Process Goals**\n\n**Outcome Goals** define WHAT you want to achieve:\n- 'Lose 10kg in 3 months'\n- 'Get promoted to manager'\n- 'Save $10,000 by December'\n\n**Process Goals** define WHAT YOU WILL DO consistently:\n- 'Exercise 4 times per week'\n- 'Complete one stretch project per month'\n- 'Automate $500/month to savings'\n\n**The Key Insight**: You cannot directly control outcomes, but you can always control your process. The best goal systems use BOTH:\n\n1. Set an inspiring outcome goal\n2. Identify the process goals that will get you there\n3. Track the process goals daily/weekly\n4. Review the outcome goal monthly\n\nThis is why Intenteo tracks both your goals AND your habits - they are two sides of the same coin.", tags: ["goals", "strategy", "planning"], readTime: "7 min" },
  { id: "goals-3", title: "Goal Review Template", description: "A structured template for conducting weekly and monthly goal reviews that keep you on track and adapting.", category: "Goals", type: "template", difficulty: "beginner", content: "**Weekly Goal Review Template**\n\n**1. Progress Check** (5 min)\n- What did I accomplish this week toward my goals?\n- What did I NOT accomplish? Why?\n- Am I on track, ahead, or behind?\n\n**2. Process Review** (5 min)\n- Did I follow my process goals this week?\n- Which habits did I maintain? Which did I miss?\n- What worked well? What needs adjusting?\n\n**3. Next Week Planning** (5 min)\n- What are my top 3 priorities next week?\n- What one thing, if done, would move the needle most?\n- What obstacles might arise and how will I handle them?\n\n**4. Reflection** (5 min)\n- What am I most grateful for this week?\n- What did I learn?\n- How am I growing?", tags: ["goals", "review", "planning"], readTime: "5 min" },

  // ─── HABITS ───
  { id: "habits-1", title: "Habit Stacking: The Power of Linked Routines", description: "Learn the habit stacking technique to seamlessly integrate new habits into your existing daily routine.", category: "Habits", type: "guide", difficulty: "beginner", content: "**Habit Stacking** is the technique of linking a new habit to an existing one.\n\n**The Formula**:\n'After I [CURRENT HABIT], I will [NEW HABIT]'\n\n**Examples**:\n- After I pour my morning coffee, I will write 3 things I am grateful for\n- After I sit down at my desk, I will review my top 3 priorities\n- After I brush my teeth at night, I will read for 10 minutes\n- After I finish lunch, I will take a 5-minute walk\n\n**Why It Works**:\nYour brain already has neural pathways for existing habits. By linking a new behavior to an established one, you piggyback on those existing neural connections.\n\n**Tips**:\n- Start with habits that take less than 2 minutes\n- Keep the stack small (2-3 habits max)\n- Be specific about when and where", tags: ["habits", "routine", "behavior"], readTime: "6 min" },
  { id: "habits-2", title: "Identity-Based Habits: Becoming vs Doing", description: "Shift from outcome-focused habits to identity-focused habits for lasting transformation.", category: "Habits", type: "article", difficulty: "intermediate", content: "**The Most Powerful Way to Change Your Habits**\n\nMost people focus on outcomes: 'I want to lose weight' or 'I want to read more.'\n\nThe most effective approach focuses on identity: 'I am becoming a healthy person' or 'I am a reader.'\n\n**Three Levels of Change**:\n1. **Outcomes**: What you get (results)\n2. **Processes**: What you do (habits and systems)\n3. **Identity**: What you believe (who you are)\n\n**The Shift**:\nInstead of: 'I am trying to quit smoking'\nSay: 'I am not a smoker'\n\nInstead of: 'I want to run a marathon'\nSay: 'I am a runner'\n\n**How to Build Identity Habits**:\n- Every action is a vote for the type of person you want to become\n- Start with one small habit that proves your new identity\n- Each time you show up, you are casting a vote\n- Over time, the votes add up and the identity becomes real", tags: ["habits", "identity", "behavior"], readTime: "8 min" },
  { id: "habits-3", title: "The Habit Troubleshooting Guide", description: "A systematic guide to diagnose why a habit is not sticking and fix the underlying issue.", category: "Habits", type: "checklist", difficulty: "intermediate", content: "**Habit Troubleshooting Checklist**\n\nWhen a habit is not sticking, work through these diagnostic questions:\n\n**1. Is the cue obvious?**\n- [ ] Is there a clear trigger?\n- [ ] Is it tied to an existing routine?\n- [ ] Have you placed visual reminders?\n\n**2. Is the craving attractive?**\n- [ ] Are you pairing it with something enjoyable?\n- [ ] Are you part of a community that does this?\n- [ ] Do you believe this habit aligns with your identity?\n\n**3. Is the response easy?**\n- [ ] Is the habit too big? (Scale it down to 2 minutes)\n- [ ] Do you have everything you need ready?\n- [ ] Is the environment set up for success?\n\n**4. Is the reward satisfying?**\n- [ ] Is there immediate positive feedback?\n- [ ] Are you tracking the habit visually?\n- [ ] Are you celebrating small wins?\n\n**5. Common Fixes**:\n- Habit too big? Make it smaller\n- Wrong time of day? Move it\n- Missing accountability? Add a partner\n- No intrinsic motivation? Reconnect to your 'why'", tags: ["habits", "troubleshooting", "behavior"], readTime: "10 min" },

  // ─── TASKS ───
  { id: "tasks-1", title: "Deep Work: Focused Execution in a Distracted World", description: "Learn the principles of deep work and how to create blocks of uninterrupted focus for your most important tasks.", category: "Tasks", type: "guide", difficulty: "intermediate", content: "**Deep Work** is the ability to focus without distraction on a cognitively demanding task.\n\n**The Deep Work Rules**:\n\n1. **Work Deeply**: Choose your deep work philosophy:\n   - Monastic: Eliminate all distractions (rare)\n   - Bimodal: dedicate defined stretches to deep work\n   - Rhythmic: Same time every day (most practical)\n   - Journalistic: Fit deep work whenever possible\n\n2. **Embrace Boredom**: Do not constantly seek stimulation. Train your focus muscle.\n\n3. **Quit Social Media** (or at least audit ruthlessly)\n\n4. **Drain the Shallows**: Minimize low-value tasks\n\n**How to Start**:\n- Block 90 minutes on your calendar\n- Turn off all notifications\n- Work on ONE task\n- Do not check email or messages\n- Track your deep work hours weekly", tags: ["productivity", "focus", "tasks"], readTime: "8 min" },
  { id: "tasks-2", title: "Time Blocking: Reclaim Your Calendar", description: "Master the time blocking technique to take control of your schedule and ensure your priorities get the time they deserve.", category: "Tasks", type: "guide", difficulty: "beginner", content: "**Time Blocking** is the practice of planning every part of your day in advance.\n\n**How to Time Block**:\n\n1. **Capture everything**: Brain dump all tasks, commitments, and habits\n2. **Estimate time**: Be realistic (add 25% buffer)\n3. **Prioritize**: Use the Eisenhower Matrix (Urgent/Important)\n4. **Block your day**: Assign every hour a specific purpose\n5. **Protect your blocks**: Treat them like appointments\n\n**Sample Time-Blocked Day**:\n- 6:00-7:00 Morning routine (exercise, journaling)\n- 7:00-9:00 Deep work block 1\n- 9:00-9:30 Email and messages\n- 9:30-11:30 Deep work block 2\n- 11:30-12:00 Admin tasks\n- 12:00-1:00 Lunch and rest\n- 1:00-3:00 Meetings and collaboration\n- 3:00-4:30 Deep work block 3\n- 4:30-5:00 Review and plan tomorrow\n\n**Pro Tip**: Leave 30-minute buffers between deep work blocks.", tags: ["productivity", "planning", "tasks"], readTime: "7 min" },
  { id: "tasks-3", title: "The Eisenhower Matrix for Priority Management", description: "Use the urgent-important matrix to categorize tasks and focus on what truly matters.", category: "Tasks", type: "framework", difficulty: "beginner", content: "**The Eisenhower Matrix**\n\n| | Urgent | Not Urgent |\n|---|---|---|\n| **Important** | DO (do immediately) | SCHEDULE (plan time for it) |\n| **Not Important** | DELEGATE (get someone else) | ELIMINATE (remove entirely) |\n\n**Quadrant 1 - DO** (Urgent + Important)\nCrises, deadlines, emergencies. Handle these now.\n\n**Quadrant 2 - SCHEDULE** (Not Urgent + Important)\nPlanning, prevention, relationship building, new opportunities. This is where success comes from. Spend most time here.\n\n**Quadrant 3 - DELEGATE** (Urgent + Not Important)\nSome meetings, many emails, other people's priorities. Delegate or minimize.\n\n**Quadrant 4 - ELIMINATE** (Not Urgent + Not Important)\nTime wasters, excessive social media, busywork. Remove ruthlessly.\n\n**The Goal**: Maximize Quadrant 2 time. This is the secret of highly effective people.", tags: ["productivity", "priorities", "tasks"], readTime: "5 min" },

  // ─── JOURNAL ───
  { id: "journal-1", title: "100 Reflection Prompts for Self-Awareness", description: "A curated collection of journaling prompts designed to deepen self-understanding and uncover blind spots.", category: "Journal", type: "prompt", difficulty: "beginner", content: "**Morning Prompts**:\n1. What am I most excited about today?\n2. What would make today great?\n3. What am I grateful for right now?\n4. What is my intention for today?\n5. If today had a theme, what would it be?\n\n**Evening Prompts**:\n1. What went well today?\n2. What did I learn?\n3. When did I feel most alive?\n4. What would I do differently?\n5. What am I proud of?\n\n**Deep Reflection Prompts**:\n1. What pattern in my life keeps repeating?\n2. What am I avoiding and why?\n3. What would I do if I were not afraid?\n4. When do I feel most authentic?\n5. What does my ideal day look like?\n\n**Relationship Prompts**:\n1. Who energizes me? Who drains me?\n2. What kind of friend am I being?\n3. What conversation am I avoiding?\n4. How can I show love better today?", tags: ["journaling", "reflection", "self-awareness"], readTime: "10 min" },
  { id: "journal-2", title: "Gratitude Journaling: The Science of Thankfulness", description: "Learn how gratitude journaling rewires your brain for happiness and how to do it effectively.", category: "Journal", type: "article", difficulty: "beginner", content: "**The Science of Gratitude**\n\nResearch shows gratitude journaling:\n- Increases happiness by 25%\n- Improves sleep quality\n- Reduces physical pain\n- Strengthens relationships\n- Builds resilience\n\n**How to Practice**:\n\n1. **Be specific**: Not 'I am grateful for my family' but 'I am grateful my daughter laughed at my joke at dinner tonight'\n\n2. **Feel the emotion**: Do not just write the words. Re-experience the feeling.\n\n3. **Add variety**: Write about different things each day\n\n4. **Include people**: Gratitude toward others is more powerful than gratitude for things\n\n5. **Look for the unexpected**: Notice surprises and delights\n\n**The 3-3-3 Method**:\nWrite 3 things you are grateful for, 3 things that went well, and 3 things you are looking forward to. Takes less than 5 minutes.", tags: ["gratitude", "journaling", "wellbeing"], readTime: "6 min" },
  { id: "journal-3", title: "Decision Journaling Framework", description: "A structured approach to documenting and learning from your decisions over time.", category: "Journal", type: "template", difficulty: "intermediate", content: "**Decision Journal Template**\n\n**The Decision**:\n- Date: ___\n- Decision: ___\n- Stakes: Low / Medium / High\n- Time horizon: Immediate / Short-term / Long-term\n\n**Context**:\n- What options did I consider?\n- What information did I have?\n- Who else was involved?\n- What was my emotional state?\n\n**Reasoning**:\n- Why did I choose this option?\n- What did I believe would happen?\n- What were my key assumptions?\n- What would change my mind?\n\n**Outcome** (fill in 30-90 days later):\n- What actually happened?\n- What did I learn?\n- Were my assumptions correct?\n- What would I do differently?\n\n**The Power of Decision Journaling**:\nOver time, you will see patterns in your decision-making. You will learn which types of decisions you make well and which ones need more careful thought.", tags: ["journaling", "decisions", "learning"], readTime: "8 min" },

  // ─── MINDFULNESS ───
  { id: "mindfulness-1", title: "Beginner's Guide to Meditation", description: "Everything you need to start a meditation practice, from your first session to building a lasting habit.", category: "Mindfulness", type: "guide", difficulty: "beginner", content: "**Your First Meditation Session**\n\n**Step 1: Set Up**\n- Find a quiet spot\n- Set a timer for 5 minutes\n- Sit comfortably (chair, cushion, or floor)\n- Close your eyes or soften your gaze\n\n**Step 2: Breathe**\n- Breathe naturally\n- Focus on the sensation of air entering and leaving your nostrils\n- When your mind wanders (it will), gently bring attention back\n\n**Step 3: Handle Thoughts**\n- Thoughts are not failures. They are part of meditation.\n- Notice the thought like a cloud passing\n- Label it gently: 'thinking'\n- Return to your breath\n\n**Step 4: End**\n- Slowly open your eyes\n- Notice how you feel\n- Do not judge the session\n\n**Building the Habit**:\n- Start with 5 minutes daily\n- Increase by 1 minute each week\n- Same time each day (morning is ideal)\n- Consistency matters more than duration", tags: ["meditation", "mindfulness", "beginner"], readTime: "8 min" },
  { id: "mindfulness-2", title: "Breathing Exercises for Every Situation", description: "A collection of evidence-based breathing techniques for stress relief, focus, energy, and sleep.", category: "Mindfulness", type: "exercise", difficulty: "beginner", content: "**5 Breathing Techniques**\n\n**1. Box Breathing (for calm)**\n- Inhale 4 seconds\n- Hold 4 seconds\n- Exhale 4 seconds\n- Hold 4 seconds\n- Repeat 4 times\n\n**2. 4-7-8 Breathing (for sleep)**\n- Inhale 4 seconds\n- Hold 7 seconds\n- Exhale 8 seconds\n- Repeat 3 times\n\n**3. Energizing Breath (for energy)**\n- Quick, forceful inhales through nose\n- Quick, forceful exhales through mouth\n- 30 breaths in 30 seconds\n- Then normal breathing\n\n**4. Extended Exhale (for anxiety)**\n- Inhale for 4 seconds\n- Exhale for 8 seconds\n- The longer exhale activates your parasympathetic nervous system\n\n**5. Morning Breath (for focus)**\n- Deep inhale through nose (4 sec)\n- Hold (4 sec)\n- Exhale through mouth (6 sec)\n- Repeat 5 times", tags: ["breathing", "mindfulness", "stress"], readTime: "5 min" },
  { id: "mindfulness-3", title: "The Scientific Benefits of Mindfulness", description: "Research-backed evidence showing how mindfulness practice transforms your brain, body, and behavior.", category: "Mindfulness", type: "article", difficulty: "beginner", content: "**What Science Says About Mindfulness**\n\n**Brain Changes** (Harvard, 2011):\n- 8 weeks of meditation increased gray matter in the hippocampus (learning and memory)\n- Decreased gray matter in the amygdala (stress and fear)\n\n**Stress Reduction** (American Psychological Association):\n- Mindfulness-based stress reduction (MBSR) reduces cortisol levels\n- Participants reported 31% reduction in perceived stress\n\n**Emotional Regulation** (JAMA Internal Medicine, 2014):\n- Mindfulness meditation reduced anxiety by 38%\n- Reduced depression by 31%\n- Reduced chronic pain by 28%\n\n**Focus and Productivity** (University of Washington, 2013):\n- Meditators stayed on task 40% longer\n- Switched tasks less frequently\n- Reported less negative emotion after task-switching\n\n**Physical Health**:\n- Lower blood pressure\n- Improved immune function\n- Better sleep quality\n- Reduced chronic inflammation\n\nThe evidence is clear: regular mindfulness practice fundamentally changes your brain and body for the better.", tags: ["mindfulness", "science", "research"], readTime: "10 min" },
  { id: "mindfulness-4", title: "Mindful Walking Practice", description: "A guided practice for turning your daily walk into a mindfulness session that grounds and restores you.", category: "Mindfulness", type: "exercise", difficulty: "beginner", content: "**Mindful Walking Practice**\n\nThis practice transforms a regular walk into a meditation in motion.\n\n**How to Practice**:\n\n1. **Start Standing**: Feel your feet on the ground. Notice the weight distribution.\n\n2. **Begin Walking Slowly**: Half your normal speed. Feel each step.\n\n3. **Focus on Sensations**:\n   - Heel touches ground\n   - Weight transfers forward\n   - Toes press off\n   - Foot lifts\n\n4. **Engage Your Senses**:\n   - What do you see? (colors, light, movement)\n   - What do you hear? (birds, wind, distant sounds)\n   - What do you feel? (air on skin, ground underfoot)\n\n5. **When Your Mind Wanders**: Gently bring attention back to your feet.\n\n6. **Duration**: 10-20 minutes\n\n**Best Settings**:\n- Nature (parks, trails, gardens)\n- Quiet streets early morning\n- Indoor hallways when weather is poor\n\n**When to Use**:\n- When feeling anxious or overwhelmed\n- As a morning centering practice\n- During a lunch break reset", tags: ["walking", "mindfulness", "exercise"], readTime: "5 min" },

  // ─── HEALTH ───
  { id: "health-1", title: "Sleep Hygiene: The Complete Guide", description: "Evidence-based strategies to improve your sleep quality, fall asleep faster, and wake up refreshed.", category: "Health", type: "guide", difficulty: "beginner", content: "**The Sleep Hygiene Checklist**\n\n**Environment**:\n- [ ] Room temperature: 65-68F (18-20C)\n- [ ] Complete darkness (blackout curtains or eye mask)\n- [ ] Quiet environment (earplugs or white noise)\n- [ ] Comfortable mattress and pillows\n- [ ] No screens in bedroom\n\n**Routine**:\n- [ ] Same bedtime every night (even weekends)\n- [ ] Same wake time every morning\n- [ ] Wind-down routine 60 minutes before bed\n- [ ] No caffeine after 2 PM\n- [ ] No heavy meals 3 hours before bed\n\n**Evening Habits**:\n- [ ] Dim lights 2 hours before bed\n- [ ] Read (physical book, not screens)\n- [ ] Light stretching or breathing exercises\n- [ ] Journal or brain dump worries\n- [ ] Avoid stimulating content\n\n**What to Avoid**:\n- Screens 1 hour before bed (blue light blocks melatonin)\n- Alcohol before bed (disrupts REM sleep)\n- Naps longer than 20 minutes\n- Irregular sleep schedule", tags: ["sleep", "health", "routine"], readTime: "8 min" },
  { id: "health-2", title: "Evening Wind-Down Routine", description: "Create a calming pre-sleep ritual that signals to your body and mind that it is time to rest.", category: "Health", type: "template", difficulty: "beginner", content: "**Evening Wind-Down Template**\n\n**90 Minutes Before Bed**:\n- Dim all lights in your home\n- Put away work devices\n- Light conversation with family or quiet activity\n\n**60 Minutes Before Bed**:\n- Put phone on Do Not Disturb\n- Make a cup of herbal tea (chamomile, valerian, or peppermint)\n- Light stretching or gentle yoga (5-10 min)\n- Take a warm shower or bath\n\n**30 Minutes Before Bed**:\n- Read a physical book (fiction or light non-fiction)\n- Practice gratitude journaling (3 things)\n- Do a breathing exercise (4-7-8 technique)\n- Review tomorrow (brief planning, not problem-solving)\n\n**In Bed**:\n- 5 minutes of body scan meditation\n- Focus on slow, deep breathing\n- If mind is racing: write thoughts on bedside notepad\n\n**Consistency is Key**: Your body will learn this routine and begin preparing for sleep automatically.", tags: ["sleep", "routine", "health"], readTime: "6 min" },
  { id: "health-3", title: "Understanding Your Circadian Rhythm", description: "Learn how your internal body clock works and how to align your schedule with it for optimal energy and health.", category: "Health", type: "article", difficulty: "intermediate", content: "**Your Circadian Rhythm Explained**\n\nYour body runs on a 24-hour internal clock that regulates sleep, energy, hormones, and body temperature.\n\n**Key Hormone Cycles**:\n- **6-8 AM**: Cortisol peaks (wake up, feel alert)\n- **10 AM - 2 PM**: Peak cognitive performance\n- **2-4 PM**: Post-lunch dip (natural low point)\n- **5-7 PM**: Peak physical performance\n- **9-10 PM**: Melatonin rises (prepare for sleep)\n- **2-4 AM**: Deepest sleep, lowest body temperature\n\n**How to Align With Your Rhythm**:\n\n1. **Morning (6-10 AM)**: Get sunlight within 30 minutes of waking. This resets your clock.\n2. **Midday (10 AM-2 PM)**: Do your most demanding cognitive work.\n3. **Afternoon (2-5 PM)**: Schedule meetings, admin, or light tasks.\n4. **Evening (5-9 PM)**: Exercise, socialize, light activities.\n5. **Night (9-10 PM)**: Wind down, dim lights, prepare for sleep.\n\n**The #1 Mistake**: Using bright screens after 9 PM. Blue light suppresses melatonin by up to 50%.", tags: ["sleep", "health", "rhythm"], readTime: "9 min" },

  // ─── LEARNING ───
  { id: "learning-1", title: "Speed Reading Techniques", description: "Practical techniques to increase your reading speed without sacrificing comprehension.", category: "Learning", type: "guide", difficulty: "intermediate", content: "**Speed Reading Fundamentals**\n\n**The Problem**: Most people read at 200-250 words per minute. With training, you can reach 400-700+ wpm.\n\n**Technique 1: Reduce Subvocalization**\n- Subvocalizing (saying words in your head) limits speed\n- Use a finger or pen to guide your eyes\n- Focus on groups of words, not individual words\n\n**Technique 2: Expand Peripheral Vision**\n- Instead of focusing on one word, see 3-5 words at once\n- Practice by widening your focus on each line\n- Use a pacer (finger or pen) to guide your eyes\n\n**Technique 3: Chunking**\n- Group words into meaningful phrases\n- Instead of 'the/cat/sat/on/the/mat'\n- Read: 'the cat sat on the mat'\n\n**Technique 4: Regression Elimination**\n- Stop going back to re-read\n- Trust your comprehension\n- If something is important, it will appear again\n\n**Practice Plan**:\n- Week 1-2: Practice with easy material (fiction)\n- Week 3-4: Increase speed by 20%\n- Week 5-6: Apply to professional reading\n- Ongoing: Track your words per minute", tags: ["reading", "learning", "speed"], readTime: "8 min" },
  { id: "learning-2", title: "Effective Note-Taking Systems", description: "Compare and choose the best note-taking method for your learning style and goals.", category: "Learning", type: "guide", difficulty: "beginner", content: "**5 Note-Taking Systems Compared**\n\n**1. Cornell Method**\nDivide page into 3 sections: cues (left), notes (right), summary (bottom)\nBest for: Lectures, structured learning\n\n**2. Mind Mapping**\nStart with central idea, branch out with related concepts\nBest for: Brainstorming, creative projects, visual learners\n\n**3. Outline Method**\nHierarchical bullet points with main topics and subtopics\nBest for: Organized note-takers, technical material\n\n**4. Zettelkasten (Slip Box)**\nEach idea on its own card, linked to related ideas\nBest for: Researchers, writers, long-term knowledge building\n\n**5. Progressive Summarization**\nTake notes, then progressively highlight and distill key points\nBest for: Digital note-takers, content creators\n\n**Choosing Your System**:\n- Student? Cornell or Outline\n- Creative? Mind Mapping\n- Researcher? Zettelkasten\n- Knowledge worker? Progressive Summarization\n\n**The Key**: The best system is the one you actually use consistently.", tags: ["learning", "notes", "productivity"], readTime: "7 min" },

  // ─── PRODUCTIVITY ───
  { id: "productivity-1", title: "The Two-Minute Rule", description: "David Allen's simple rule that eliminates procrastination and builds momentum for your most important tasks.", category: "Productivity", type: "framework", difficulty: "beginner", content: "**The Two-Minute Rule** (from Getting Things Done)\n\n**Rule 1**: If it takes less than 2 minutes, do it NOW.\n- Responding to a quick email\n- Filing a document\n- Making a quick phone call\n- Putting something away\n\n**Rule 2**: When starting a new habit, it should take less than 2 minutes.\n- 'Read before bed' becomes 'read one page'\n- 'Run 3 miles' becomes 'put on running shoes'\n- 'Study for exam' becomes 'open notebook'\n\n**Why It Works**:\n- Eliminates the buildup of small tasks\n- Creates momentum for bigger tasks\n- Builds the habit of starting\n- Reduces mental clutter\n\n**The Insight**: The habit of starting is more important than the habit of finishing. Once you start, continuing becomes natural.\n\n**Apply to Intenteo**: When you open the app, what is the 2-minute action that moves you forward? Check one task. Log one habit. Write one sentence in your journal.", tags: ["productivity", "habits", "efficiency"], readTime: "4 min" },
  { id: "productivity-2", title: "Planning Techniques That Actually Work", description: "Master the weekly, daily, and monthly planning rituals that top performers use to stay focused and effective.", category: "Productivity", type: "guide", difficulty: "beginner", content: "**The Planning Ritual**\n\n**Weekly Review (Sunday, 30 min)**:\n1. Review last week: What was accomplished? What was not?\n2. Check calendar for upcoming commitments\n3. Identify top 3 goals for the week\n4. Schedule deep work blocks\n5. Plan meals and exercise\n6. Set intentions\n\n**Daily Planning (Evening, 5 min)**:\n1. Review tomorrow's calendar\n2. Choose top 3 priorities\n3. Time-block your day\n4. Prepare anything needed (clothes, documents, meals)\n\n**Monthly Review (First of month, 60 min)**:\n1. Review goals and milestones\n2. Assess progress on projects\n3. Check finances\n4. Plan major commitments\n5. Set monthly focus areas\n6. Celebrate wins\n\n**The Golden Rule**: Plan the week, win the day. Do not skip your planning ritual.", tags: ["productivity", "planning", "goals"], readTime: "7 min" },

  // ─── LEADERSHIP ───
  { id: "leadership-1", title: "The Art of Influence Without Authority", description: "Learn how to lead, inspire, and create change even when you do not have formal power or position.", category: "Leadership", type: "article", difficulty: "intermediate", content: "**Leading Without Authority**\n\nMost leadership happens without a title. Here is how to influence effectively:\n\n**1. Build Trust First**\n- Be consistent in your words and actions\n- Follow through on small commitments\n- Be honest, even when it is uncomfortable\n- Show genuine interest in others\n\n**2. Understand Others' Goals**\n- Ask: What does this person care about?\n- Find alignment between their goals and yours\n- Frame your ideas in terms of their benefits\n- Listen more than you speak\n\n**3. Create Quick Wins**\n- Start with small, achievable changes\n- Build momentum through early success\n- Use success to gain support for bigger changes\n\n**4. Be the Solution**\n- Identify problems others are ignoring\n- Propose solutions, not just complaints\n- Take initiative without being asked\n- Make your leader's job easier\n\n**5. Develop Your Network**\n- Help others without expecting anything in return\n- Connect people who would benefit from knowing each other\n- Be known as someone who adds value", tags: ["leadership", "influence", "communication"], readTime: "8 min" },

  // ─── FINANCE ───
  { id: "finance-1", title: "Budgeting for Beginners", description: "A simple, practical guide to creating and maintaining a budget that actually works for your lifestyle.", category: "Finance", type: "guide", difficulty: "beginner", content: "**The Simple Budget Framework**\n\n**Step 1: Calculate Income**\n- All sources of regular income\n- Use your take-home (after-tax) amount\n\n**Step 2: Track Spending**\n- Review last 2 months of bank statements\n- Categorize every expense\n\n**Step 3: Apply the 50/30/20 Rule**\n- 50% Needs: Rent, food, transport, utilities, insurance\n- 30% Wants: Entertainment, dining out, hobbies, shopping\n- 20% Savings & Debt: Emergency fund, investments, debt payoff\n\n**Step 4: Automate**\n- Set up automatic transfers for savings\n- Pay bills automatically\n- Use separate accounts for spending and savings\n\n**Step 5: Review Weekly**\n- 10-minute check every Sunday\n- Compare actual vs planned spending\n- Adjust for the coming week\n\n**The Key Insight**: A budget is not about restricting yourself. It is about being intentional with your money so it goes toward what matters most.", tags: ["finance", "budgeting", "money"], readTime: "8 min" },
  { id: "finance-2", title: "Building an Emergency Fund", description: "Why every person needs an emergency fund and the step-by-step plan to build one from zero.", category: "Finance", type: "guide", difficulty: "beginner", content: "**Your Emergency Fund Roadmap**\n\n**Why It Matters**:\n- 78% of Americans live paycheck to paycheck\n- Unexpected expenses are the #1 cause of debt\n- An emergency fund prevents financial spirals\n\n**The Target**: 3-6 months of essential expenses\n\n**How to Calculate**:\n- Monthly rent/mortgage: ___\n- Monthly food: ___\n- Monthly transport: ___\n- Monthly utilities: ___\n- Monthly insurance: ___\n- Total essentials: ___\n- Emergency fund target: ___ x 3-6\n\n**The Build-Up Plan**:\n\n**Phase 1: Starter Fund ($1,000)**\n- Sell unused items\n- Pick up extra work\n- Cut one expense for 3 months\n- Timeline: 1-3 months\n\n**Phase 2: One Month of Expenses**\n- Automate $50-200/month to savings\n- Redirect windfalls (tax refunds, bonuses)\n- Timeline: 3-6 months\n\n**Phase 3: Full Fund (3-6 months)**\n- Continue automating\n- Increase contributions with income growth\n- Timeline: 12-24 months\n\n**Where to Keep It**: High-yield savings account (accessible but separate from daily checking)", tags: ["finance", "savings", "emergency"], readTime: "7 min" },

  // ─── RELATIONSHIPS ───
  { id: "relationships-1", title: "Active Listening: The Most Undervalued Skill", description: "Learn the art of truly hearing others and how it transforms every relationship in your life.", category: "Relationships", type: "guide", difficulty: "beginner", content: "**The 5 Levels of Listening**\n\n**Level 1: Ignoring** - Not listening at all\n**Level 2: Pretend Listening** - 'Uh-huh, yeah, right'\n**Level 3: Selective Listening** - Hearing only parts\n**Level 4: Attentive Listening** - Hearing all words\n**Level 5: Empathic Listening** - Understanding the feeling behind the words\n\n**How to Practice Empathic Listening**:\n\n1. **Be Present**: Put away your phone. Make eye contact. Face the person.\n\n2. **Do Not Interrupt**: Let them finish completely. Count to 3 after they stop.\n\n3. **Reflect Back**: 'It sounds like you are feeling...'\n\n4. **Ask Questions**: 'Can you tell me more about...?'\n\n5. **Validate**: 'That makes sense because...'\n\n6. **Do Not Fix**: Most people want to be heard, not solved.\n\n**The Impact**: People who feel truly listened to trust more deeply, share more openly, and feel more connected. This is the foundation of every strong relationship.", tags: ["relationships", "communication", "listening"], readTime: "7 min" },

  // ─── FAITH ───
  { id: "faith-1", title: "A Guide to Personal Prayer", description: "A practical guide to developing a meaningful, consistent prayer life that deepens your spiritual connection.", category: "Faith", type: "guide", difficulty: "beginner", content: "**Developing Your Prayer Life**\n\n**The ACTS Model**:\n- **A**doration: Praise God for who He is\n- **C**onfession: Acknowledge areas where you fall short\n- **T**hanksgiving: Express gratitude for what He has done\n- **S**upplication: Present your requests and needs\n\n**Practical Tips**:\n\n1. **Set a Time**: Morning prayer sets the tone for the day\n2. **Find a Quiet Place**: Minimize distractions\n3. **Start Small**: 5 minutes is enough to begin\n4. **Use a Journal**: Write your prayers to stay focused\n5. **Be Honest**: God already knows your heart\n6. **Listen**: Prayer is a conversation, not a monologue\n\n**When You Do Not Know What to Pray**:\n- Pray Scripture\n- Pray for others\n- Simply sit in God's presence\n- Say: 'Lord, I do not know what to pray, but you know what I need'\n\n**The Goal**: Not perfect words, but authentic connection.", tags: ["faith", "prayer", "spiritual"], readTime: "6 min" },
  { id: "faith-2", title: "Bible Study Methods for Beginners", description: "Simple, effective methods for studying Scripture that lead to understanding and application.", category: "Faith", type: "guide", difficulty: "beginner", content: "**4 Bible Study Methods**\n\n**1. SOAP Method**\n- **S**cripture: Write the verse that stands out\n- **O**bservation: What do you notice? Context, meaning, key words\n- **A**pplication: How does this apply to your life today?\n- **P**rayer: Pray about what you learned\n\n**2. Chapter Summary Method**\n- Read the chapter through once\n- Summarize each paragraph in one sentence\n- Identify the main theme\n- Note any commands, promises, or warnings\n\n**3. Word Study**\n- Choose a key word from the passage\n- Look up its meaning in a concordance\n- See how it is used elsewhere in Scripture\n- Reflect on its significance\n\n**4. Compare and Contrast**\n- Read two passages on the same topic\n- Note similarities and differences\n- Ask: What is God teaching through both?\n\n**Getting Started**:\n- Start with the Gospel of John\n- Read one chapter per day\n- Use one method per week\n- Journal what you learn", tags: ["faith", "bible", "study"], readTime: "8 min" },

  // ─── PERSONAL GROWTH ───
  { id: "growth-1", title: "The Growth Mindset: Embracing Challenges", description: "Understand the difference between fixed and growth mindsets and how it shapes your potential.", category: "Personal Growth", type: "article", difficulty: "beginner", content: "**Fixed vs Growth Mindset**\n\n**Fixed Mindset** (Carol Dweck):\n- 'I am either good at this or I am not'\n- Avoids challenges\n- Gives up easily\n- Sees effort as pointless\n- Ignores useful criticism\n\n**Growth Mindset**:\n- 'I can improve with effort and strategy'\n- Embraces challenges\n- Persists through setbacks\n- Sees effort as the path to mastery\n- Learns from criticism\n\n**How to Develop a Growth Mindset**:\n\n1. **Add 'yet'**: 'I cannot do this... yet'\n\n2. **Celebrate effort, not just results**: 'You worked really hard on that'\n\n3. **Reframe failure**: 'What did I learn?' instead of 'I failed'\n\n4. **Ask for feedback**: Seek constructive criticism\n\n5. **Study how experts began**: Everyone started as a beginner\n\n**The Key Insight**: Your abilities are not fixed. Your brain is like a muscle that grows stronger with use. Every challenge is an opportunity to grow.", tags: ["growth", "mindset", "personal"], readTime: "6 min" },
  { id: "growth-2", title: "Breaking Bad Habits: The Evidence-Based Approach", description: "Science-backed strategies for eliminating unwanted behaviors and replacing them with positive ones.", category: "Personal Growth", type: "guide", difficulty: "beginner", content: "**How to Break a Bad Habit**\n\n**Understanding the Habit Loop**:\n- **Cue**: The trigger that starts the behavior\n- **Routine**: The behavior itself\n- **Reward**: The benefit you get from the behavior\n\n**The Strategy**: Do NOT try to eliminate a habit. REPLACE it.\n\n**Step 1: Identify the Cue**\n- Where are you? What time is it? Who is around?\n- What emotion are you feeling?\n- What immediately preceded the behavior?\n\n**Step 2: Understand the Reward**\n- What need is this habit meeting?\n- Boredom? Stress? Loneliness? Hunger?\n\n**Step 3: Find a Better Routine**\n- Boredom: Read, go for a walk, call a friend\n- Stress: Deep breathing, stretching, journaling\n- Loneliness: Reach out to someone, visit a community\n- Hunger: Healthy snack, water, tea\n\n**Step 4: Change Your Environment**\n- Remove cues for the bad habit\n- Add cues for the good habit\n- Make the bad habit difficult and the good habit easy\n\n**The 21-Day Myth**: Habits do not form in 21 days. Research shows 66 days on average. Be patient.", tags: ["habits", "behavior", "growth"], readTime: "8 min" },
]

export function getResourcesByCategory(category: ResourceCategory): Resource[] {
  return ALL_RESOURCES.filter(r => r.category === category)
}

export function getResourcesByType(type: ResourceType): Resource[] {
  return ALL_RESOURCES.filter(r => r.type === type)
}

export function getResourcesByTracker(trackerId: string): Resource[] {
  const categories = TRACKER_RESOURCE_MAP[trackerId] || []
  return ALL_RESOURCES.filter(r => categories.includes(r.category))
}

export function searchResources(query: string): Resource[] {
  const q = query.toLowerCase()
  return ALL_RESOURCES.filter(r =>
    r.title.toLowerCase().includes(q) ||
    r.description.toLowerCase().includes(q) ||
    r.tags.some(t => t.toLowerCase().includes(q)) ||
    r.category.toLowerCase().includes(q)
  )
}

export function getRecentlyViewedResources(): string[] {
  if (typeof window === "undefined") return []
  try {
    return JSON.parse(localStorage.getItem("intenteo-recent-resources") || "[]")
  } catch { return [] }
}

export function addRecentlyViewedResource(id: string): void {
  const recent = getRecentlyViewedResources().filter(r => r !== id)
  recent.unshift(id)
  localStorage.setItem("intenteo-recent-resources", JSON.stringify(recent.slice(0, 20)))
}

export function getSavedResources(): string[] {
  if (typeof window === "undefined") return []
  try {
    return JSON.parse(localStorage.getItem("intenteo-saved-resources") || "[]")
  } catch { return [] }
}

export function toggleSavedResource(id: string): void {
  const saved = getSavedResources()
  if (saved.includes(id)) {
    localStorage.setItem("intenteo-saved-resources", JSON.stringify(saved.filter(s => s !== id)))
  } else {
    saved.push(id)
    localStorage.setItem("intenteo-saved-resources", JSON.stringify(saved))
  }
}

export function isResourceSaved(id: string): boolean {
  return getSavedResources().includes(id)
}
