"use client"

import { Task, TaskStatus, TaskPriority, TaskEnergy } from "./types"

const now = new Date().toISOString()
const today = new Date().toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })
const tomorrow = new Date(Date.now() + 86400000).toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })

export const sampleTasks: Task[] = [
  {
    id: "1",
    title: "Review Q2 strategy document",
    purpose: "Ensure alignment with long-term vision",
    whyItMatters: "Strategic alignment drives every successful quarter. Without this review, the team risks misallocation of resources.",
    futureSelfAlignment: "Becoming a strategic leader who sees the big picture",
    futureSelfBadge: "Strategic Leader",
    connectedGoal: "Q2 Revenue Growth",
    projectName: "Leadership Development",
    category: "Deep Work",
    priority: "high",
    intentScore: 85,
    deadline: today,
    dueTime: "9:00 AM - 11:00 AM",
    estimatedDuration: 120,
    energyRequired: "high",
    tags: ["Strategy", "Leadership"],
    subtasks: [
      { id: "s1", title: "Read previous quarter review", completed: true },
      { id: "s2", title: "Analyze KPI trends", completed: true },
      { id: "s3", title: "Draft recommendations", completed: false },
      { id: "s4", title: "Prepare slides for board review", completed: false },
    ],
    attachments: [{ id: "a1", name: "Q2-Strategy.pdf", type: "pdf", url: "#" }],
    comments: [{ id: "c1", text: "Focus on the new market expansion section", author: "Sarah Chen", createdAt: now }],
    activity: [
      { id: "ac1", action: "Created task", timestamp: now },
      { id: "ac2", action: "Added subtask: Read previous quarter review", timestamp: now },
    ],
    dependencies: [],
    status: "in-progress",
    completed: false,
    completionPercent: 50,
    isRecurring: false,
    recurrence: "none",
    location: "Office - Conference Room A",
    notes: "Review with the leadership team. Bring the competitive analysis from last week.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 30,
    aiSuggestion: "This task usually takes 90 minutes. You are most productive between 9-11 AM. Consider starting at 9:00 AM.",
  },
  {
    id: "2",
    title: "Call with design team",
    purpose: "Collaborate on product improvements",
    whyItMatters: "Design decisions made today will shape the user experience for the next 6 months.",
    futureSelfAlignment: "Building products that change lives",
    futureSelfBadge: "Product Visionary",
    connectedGoal: "Product Excellence",
    projectName: "Product Redesign",
    category: "Meeting",
    priority: "medium",
    intentScore: 70,
    deadline: today,
    dueTime: "11:00 AM - 11:30 AM",
    estimatedDuration: 30,
    energyRequired: "medium",
    tags: ["Design", "Collaboration"],
    subtasks: [
      { id: "s5", title: "Review latest mockups", completed: true },
      { id: "s6", title: "Prepare feedback notes", completed: false },
    ],
    attachments: [],
    comments: [],
    activity: [{ id: "ac3", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: true,
    recurrence: "weekly",
    location: "Zoom",
    notes: "Join from the link in calendar invite.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 15,
    aiSuggestion: "Move this to 2 PM when your energy dips — use deep work slots for strategy tasks.",
  },
  {
    id: "3",
    title: "Morning journal entry",
    purpose: "Reflect on goals and set daily intention",
    whyItMatters: "Journaling builds self-awareness and keeps you aligned with your values.",
    futureSelfAlignment: "Staying mindful and intentional",
    futureSelfBadge: "Mindful Achiever",
    connectedGoal: "Daily Mindfulness",
    projectName: "Personal Growth",
    category: "Personal",
    priority: "low",
    intentScore: 95,
    deadline: today,
    dueTime: "7:00 AM",
    estimatedDuration: 15,
    energyRequired: "low",
    tags: ["Journal", "Reflection"],
    subtasks: [],
    attachments: [],
    comments: [],
    activity: [{ id: "ac4", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "completed",
    completed: true,
    completionPercent: 100,
    isRecurring: true,
    recurrence: "daily",
    location: "Home",
    notes: "Write about what matters most today.",
    voiceNotes: [],
    calendarSync: false,
    createdAt: now,
    updatedAt: now,
    xp: 10,
  },
  {
    id: "4",
    title: "Prepare presentation slides",
    purpose: "Share insights with the team",
    whyItMatters: "Your ability to communicate ideas clearly accelerates team alignment.",
    futureSelfAlignment: "Becoming a better communicator",
    futureSelfBadge: "Communication Pro",
    connectedGoal: "Team Alignment",
    projectName: "Leadership Development",
    category: "Deep Work",
    priority: "high",
    intentScore: 80,
    deadline: tomorrow,
    dueTime: "10:00 AM",
    estimatedDuration: 90,
    energyRequired: "high",
    tags: ["Presentation", "Communication"],
    subtasks: [
      { id: "s7", title: "Outline key talking points", completed: false },
      { id: "s8", title: "Design slide templates", completed: false },
      { id: "s9", title: "Add data visualizations", completed: false },
    ],
    attachments: [],
    comments: [],
    activity: [{ id: "ac5", action: "Created task", timestamp: now }],
    dependencies: [{ id: "d1", taskId: "1", title: "Review Q2 strategy document" }],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: false,
    recurrence: "none",
    location: "Office",
    notes: "Use the new brand guidelines. Include the competitive analysis slide.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 25,
    aiSuggestion: "Break into subtasks: outline → design → data → review.",
  },
  {
    id: "5",
    title: "Read 30 minutes",
    purpose: "Continuous learning and growth",
    whyItMatters: "Reading compounds knowledge over time. 30 minutes daily = 50+ books per year.",
    futureSelfAlignment: "Becoming a lifelong learner",
    futureSelfBadge: "Lifelong Learner",
    connectedGoal: "Read 50 Books This Year",
    projectName: "Personal Growth",
    category: "Learning",
    priority: "medium",
    intentScore: 75,
    deadline: today,
    dueTime: "9:00 PM",
    estimatedDuration: 30,
    energyRequired: "low",
    tags: ["Reading", "Growth"],
    subtasks: [],
    attachments: [],
    comments: [],
    activity: [{ id: "ac6", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: true,
    recurrence: "daily",
    location: "Home",
    notes: "Currently reading: Atomic Habits by James Clear",
    voiceNotes: [],
    calendarSync: false,
    createdAt: now,
    updatedAt: now,
    xp: 10,
  },
  {
    id: "6",
    title: "Workout session",
    purpose: "Maintain physical and mental health",
    whyItMatters: "Physical fitness directly impacts cognitive performance and emotional resilience.",
    futureSelfAlignment: "Becoming the strongest version of myself",
    futureSelfBadge: "Peak Performer",
    connectedGoal: "Physical Fitness",
    projectName: "Health & Wellness",
    category: "Health",
    priority: "high",
    intentScore: 90,
    deadline: today,
    dueTime: "6:00 PM",
    estimatedDuration: 60,
    energyRequired: "high",
    tags: ["Fitness", "Health"],
    subtasks: [
      { id: "s10", title: "Warm up - 10 min", completed: false },
      { id: "s11", title: "Strength training - 30 min", completed: false },
      { id: "s12", title: "Cardio - 15 min", completed: false },
      { id: "s13", title: "Cool down - 5 min", completed: false },
    ],
    attachments: [],
    comments: [],
    activity: [{ id: "ac7", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: true,
    recurrence: "daily",
    location: "Gym",
    notes: "Focus on upper body today. Track reps.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 20,
    aiSuggestion: "You usually skip workouts on Fridays. Consider moving to 6 AM on weekdays.",
  },
  {
    id: "7",
    title: "Write project proposal",
    purpose: "Secure stakeholder buy-in for Q3 initiative",
    whyItMatters: "This proposal could unlock a $200K budget for the innovation lab.",
    futureSelfAlignment: "Becoming a trusted advisor to leadership",
    futureSelfBadge: "Trusted Advisor",
    connectedGoal: "Q3 Budget Approval",
    projectName: "Innovation Lab",
    category: "Deep Work",
    priority: "high",
    intentScore: 88,
    deadline: tomorrow,
    dueTime: "2:00 PM",
    estimatedDuration: 180,
    energyRequired: "high",
    tags: ["Writing", "Strategy"],
    subtasks: [
      { id: "s14", title: "Executive summary", completed: false },
      { id: "s15", title: "Market analysis", completed: false },
      { id: "s16", title: "Budget breakdown", completed: false },
      { id: "s17", title: "Risk assessment", completed: false },
    ],
    attachments: [],
    comments: [],
    activity: [{ id: "ac8", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: false,
    recurrence: "none",
    location: "Office",
    notes: "Review with finance team before submission.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 35,
    aiSuggestion: "Break into 4 sessions of 45 minutes with 15-minute breaks.",
  },
  {
    id: "8",
    title: "Evening reflection",
    purpose: "Review the day and plan tomorrow",
    whyItMatters: "Daily reflection accelerates personal growth and prevents burnout.",
    futureSelfAlignment: "Living with intentionality",
    futureSelfBadge: "Intentional Living",
    connectedGoal: "Daily Mindfulness",
    projectName: "Personal Growth",
    category: "Personal",
    priority: "low",
    intentScore: 92,
    deadline: today,
    dueTime: "8:00 PM",
    estimatedDuration: 15,
    energyRequired: "low",
    tags: ["Reflection", "Growth"],
    subtasks: [],
    attachments: [],
    comments: [],
    activity: [{ id: "ac9", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: true,
    recurrence: "daily",
    location: "Home",
    notes: "Write 3 things that went well and 1 thing to improve.",
    voiceNotes: [],
    calendarSync: false,
    createdAt: now,
    updatedAt: now,
    xp: 10,
  },
  {
    id: "9",
    title: "Team standup",
    purpose: "Align on daily priorities and blockers",
    whyItMatters: "Quick daily syncs keep the team moving at full speed.",
    futureSelfAlignment: "Becoming an effective team leader",
    futureSelfBadge: "Team Leader",
    connectedGoal: "Team Alignment",
    projectName: "Leadership Development",
    category: "Meeting",
    priority: "medium",
    intentScore: 65,
    deadline: today,
    dueTime: "9:30 AM",
    estimatedDuration: 15,
    energyRequired: "low",
    tags: ["Team", "Daily"],
    subtasks: [],
    attachments: [],
    comments: [],
    activity: [{ id: "ac10", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "completed",
    completed: true,
    completionPercent: 100,
    isRecurring: true,
    recurrence: "daily",
    location: "Zoom",
    notes: "Keep it to 15 minutes max.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 5,
  },
  {
    id: "10",
    title: "Meditate for 10 minutes",
    purpose: "Cultivate mental clarity and reduce stress",
    whyItMatters: "Meditation rewires the brain for focus, calm, and resilience.",
    futureSelfAlignment: "Becoming mentally unshakable",
    futureSelfBadge: "Mind Master",
    connectedGoal: "Daily Mindfulness",
    projectName: "Personal Growth",
    category: "Personal",
    priority: "medium",
    intentScore: 80,
    deadline: today,
    dueTime: "7:30 AM",
    estimatedDuration: 10,
    energyRequired: "low",
    tags: ["Meditation", "Health"],
    subtasks: [],
    attachments: [],
    comments: [],
    activity: [{ id: "ac11", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "completed",
    completed: true,
    completionPercent: 100,
    isRecurring: true,
    recurrence: "daily",
    location: "Home",
    notes: "Use the Headspace app.",
    voiceNotes: [],
    calendarSync: false,
    createdAt: now,
    updatedAt: now,
    xp: 10,
  },
  {
    id: "11",
    title: "Code review for feature branch",
    purpose: "Maintain code quality and share knowledge",
    whyItMatters: "Good code reviews prevent bugs and spread best practices.",
    futureSelfAlignment: "Becoming a senior engineer",
    futureSelfBadge: "Code Guardian",
    connectedGoal: "Technical Excellence",
    projectName: "Product Redesign",
    category: "Work",
    priority: "medium",
    intentScore: 72,
    deadline: tomorrow,
    dueTime: "3:00 PM",
    estimatedDuration: 45,
    energyRequired: "medium",
    tags: ["Engineering", "Quality"],
    subtasks: [
      { id: "s18", title: "Review PR #234", completed: false },
      { id: "s19", title: "Review PR #235", completed: false },
    ],
    attachments: [],
    comments: [],
    activity: [{ id: "ac12", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: false,
    recurrence: "none",
    location: "Office",
    notes: "Focus on the authentication module changes.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 15,
  },
  {
    id: "12",
    title: "Plan weekend trip",
    purpose: "Recharge and create memories",
    whyItMatters: "Rest and adventure fuel creativity and prevent burnout.",
    futureSelfAlignment: "Living a balanced, fulfilling life",
    futureSelfBadge: "Life Explorer",
    connectedGoal: "Work-Life Balance",
    projectName: "Personal",
    category: "Personal",
    priority: "low",
    intentScore: 60,
    deadline: "Friday",
    dueTime: "Anytime",
    estimatedDuration: 30,
    energyRequired: "low",
    tags: ["Travel", "Fun"],
    subtasks: [
      { id: "s20", title: "Research destinations", completed: false },
      { id: "s21", title: "Book accommodation", completed: false },
      { id: "s22", title: "Plan activities", completed: false },
    ],
    attachments: [],
    comments: [],
    activity: [{ id: "ac13", action: "Created task", timestamp: now }],
    dependencies: [],
    status: "pending",
    completed: false,
    completionPercent: 0,
    isRecurring: false,
    recurrence: "none",
    location: "Home",
    notes: "Look into the mountain cabin option.",
    voiceNotes: [],
    calendarSync: true,
    createdAt: now,
    updatedAt: now,
    xp: 10,
  },
]

export function getTaskStats(tasks: Task[]) {
  const total = tasks.length
  const completed = tasks.filter((t) => t.completed).length
  const remaining = total - completed
  const completionRate = total > 0 ? Math.round((completed / total) * 100) : 0
  const totalXP = tasks.filter((t) => t.completed).reduce((a, b) => a + b.xp, 0)
  const avgIntentScore = completed > 0
    ? Math.round(tasks.filter((t) => t.completed).reduce((a, b) => a + b.intentScore, 0) / completed)
    : 0
  const deepWorkMinutes = tasks
    .filter((t) => t.category === "Deep Work" && t.completed)
    .reduce((a, b) => a + b.estimatedDuration, 0)
  const highEnergyTasks = tasks.filter((t) => t.energyRequired === "high" && !t.completed)
  const lowEnergyTasks = tasks.filter((t) => t.energyRequired === "low" && !t.completed)

  return {
    total,
    completed,
    remaining,
    completionRate,
    totalXP,
    avgIntentScore,
    deepWorkMinutes,
    highEnergyTasks: highEnergyTasks.length,
    lowEnergyTasks: lowEnergyTasks.length,
  }
}
