"use client"

import { Task } from "./types"

const now = new Date().toISOString()

function isoDate(d: Date) {
  return d.toISOString().split("T")[0]
}
function isoDateOffset(offset: number) {
  return isoDate(new Date(Date.now() + 86400000 * offset))
}
function displayDate(d: Date) {
  return d.toLocaleDateString("en-US", { weekday: "long", month: "short", day: "numeric" })
}

const todayISO = isoDateOffset(0)
const tomorrowISO = isoDateOffset(1)
const d1ISO = isoDateOffset(-1)
const d2ISO = isoDateOffset(-2)
const d3ISO = isoDateOffset(-3)
const d4ISO = isoDateOffset(-4)
const d5ISO = isoDateOffset(-5)
const d7ISO = isoDateOffset(-7)

const today = displayDate(new Date(Date.now()))
const tomorrow = displayDate(new Date(Date.now() + 86400000))
const yesterday = displayDate(new Date(Date.now() - 86400000))
const threeDaysAgo = displayDate(new Date(Date.now() - 86400000 * 3))
const fiveDaysAgo = displayDate(new Date(Date.now() - 86400000 * 5))
const lastWeek = displayDate(new Date(Date.now() - 86400000 * 7))

function nextMondayISO() {
  const d = new Date()
  const day = d.getDay()
  const diff = ((1 - day + 7) % 7) || 7
  return isoDate(new Date(d.getTime() + diff * 86400000))
}

export const sampleTasks: Task[] = [
  // ─── Yesterday ──────────────────────────────────
  {
    id: "past-1",
    title: "Morning meditation",
    whyItMatters: "Start the day with clarity.",
    priority: "maintenance",
    deadline: yesterday,
    date: d1ISO,
    dueTime: "7:00 AM",
    timeRange: "7:00 AM \u2013 7:15 AM",
    estimatedDuration: 15,
    notes: "",
    subtasks: [
      { id: "ps1", title: "Guided breathing", completed: true },
      { id: "ps2", title: "Gratitude journaling", completed: true },
    ],
    recurrence: "daily",
    completed: true,
    order: 0,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    dailyCompletions: { [d1ISO]: true },
  },
  {
    id: "past-2",
    title: "Review pull requests",
    whyItMatters: "Keep the codebase clean.",
    priority: "progress",
    deadline: yesterday,
    date: d1ISO,
    dueTime: "10:00 AM",
    timeRange: "10:00 AM \u2013 11:00 AM",
    estimatedDuration: 60,
    notes: "",
    subtasks: [],
    recurrence: "none",
    completed: true,
    order: 1,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "past-3",
    title: "Team standup",
    whyItMatters: "Align with the team.",
    priority: "progress",
    deadline: yesterday,
    date: d1ISO,
    dueTime: "9:30 AM",
    timeRange: "9:30 AM \u2013 9:45 AM",
    estimatedDuration: 15,
    notes: "",
    subtasks: [],
    recurrence: "daily",
    completed: true,
    order: 2,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    dailyCompletions: { [d1ISO]: true },
  },
  {
    id: "past-4",
    title: "Evening reflection",
    whyItMatters: "Daily reflection accelerates growth.",
    priority: "maintenance",
    deadline: yesterday,
    date: d1ISO,
    dueTime: "8:00 PM",
    timeRange: "8:00 PM \u2013 8:15 PM",
    estimatedDuration: 15,
    notes: "",
    subtasks: [],
    recurrence: "daily",
    completed: false,
    order: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    dailyCompletions: {},
  },
  // ─── Two Days Ago ────────────────────────────────
  {
    id: "past-d2-1",
    title: "Write blog post",
    whyItMatters: "Content marketing drives traffic.",
    priority: "priority",
    deadline: displayDate(new Date(Date.now() - 86400000 * 2)),
    date: d2ISO,
    dueTime: "2:00 PM",
    timeRange: "2:00 PM \u2013 4:00 PM",
    estimatedDuration: 120,
    notes: "",
    subtasks: [
      { id: "pd2-1", title: "Outline draft", completed: true },
      { id: "pd2-2", title: "Write introduction", completed: true },
      { id: "pd2-3", title: "Add images", completed: false },
    ],
    recurrence: "none",
    completed: false,
    order: 0,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "past-d2-2",
    title: "Grocery shopping",
    whyItMatters: "Healthy meals fuel productive days.",
    priority: "maintenance",
    deadline: displayDate(new Date(Date.now() - 86400000 * 2)),
    date: d2ISO,
    dueTime: "5:00 PM",
    timeRange: "5:00 PM \u2013 5:45 PM",
    estimatedDuration: 45,
    notes: "",
    subtasks: [],
    recurrence: "weekly",
    completed: true,
    order: 1,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  // ─── Three Days Ago ──────────────────────────────
  {
    id: "past-d3-1",
    title: "Update resume",
    whyItMatters: "Always be prepared for opportunities.",
    priority: "progress",
    deadline: threeDaysAgo,
    date: d3ISO,
    dueTime: "11:00 AM",
    timeRange: "11:00 AM \u2013 12:00 PM",
    estimatedDuration: 60,
    notes: "",
    subtasks: [
      { id: "pd3-1", title: "Add recent projects", completed: true },
      { id: "pd3-2", title: "Update skills section", completed: true },
    ],
    recurrence: "none",
    completed: true,
    order: 0,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "past-d3-2",
    title: "Clean the house",
    whyItMatters: "A clean space supports a clear mind.",
    priority: "maintenance",
    deadline: threeDaysAgo,
    date: d3ISO,
    dueTime: "3:00 PM",
    timeRange: "3:00 PM \u2013 4:00 PM",
    estimatedDuration: 60,
    notes: "",
    subtasks: [],
    recurrence: "weekly",
    completed: true,
    order: 1,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  // ─── Four Days Ago ───────────────────────────────
  {
    id: "past-d4-1",
    title: "Prayer journal",
    whyItMatters: "Spiritual discipline anchors the mind.",
    priority: "maintenance",
    deadline: displayDate(new Date(Date.now() - 86400000 * 4)),
    date: d4ISO,
    dueTime: "7:00 AM",
    timeRange: "7:00 AM \u2013 7:30 AM",
    estimatedDuration: 30,
    notes: "",
    subtasks: [],
    recurrence: "daily",
    completed: true,
    order: 0,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    dailyCompletions: { [d4ISO]: true },
  },
  {
    id: "past-d4-2",
    title: "Grocery shopping",
    whyItMatters: "Healthy meals fuel productive days.",
    priority: "maintenance",
    deadline: displayDate(new Date(Date.now() - 86400000 * 4)),
    date: d4ISO,
    dueTime: "5:00 PM",
    timeRange: "5:00 PM \u2013 5:45 PM",
    estimatedDuration: 45,
    notes: "",
    subtasks: [],
    recurrence: "weekly",
    completed: true,
    order: 1,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "past-d4-3",
    title: "Read 30 minutes",
    whyItMatters: "Reading compounds knowledge over time.",
    priority: "maintenance",
    deadline: displayDate(new Date(Date.now() - 86400000 * 4)),
    date: d4ISO,
    dueTime: "9:00 PM",
    timeRange: "9:00 PM \u2013 9:30 PM",
    estimatedDuration: 30,
    notes: "",
    subtasks: [],
    recurrence: "daily",
    completed: false,
    order: 2,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    dailyCompletions: {},
  },
  // ─── Five Days Ago ───────────────────────────────
  {
    id: "past-d5-1",
    title: "Review proposal",
    whyItMatters: "Thorough review prevents costly revisions.",
    priority: "priority",
    deadline: fiveDaysAgo,
    date: d5ISO,
    dueTime: "10:00 AM",
    timeRange: "10:00 AM \u2013 12:00 PM",
    estimatedDuration: 120,
    notes: "",
    subtasks: [
      { id: "pd5-1", title: "Check budget figures", completed: true },
      { id: "pd5-2", title: "Verify timeline", completed: true },
    ],
    recurrence: "none",
    completed: true,
    order: 0,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "past-d5-2",
    title: "Team meeting",
    whyItMatters: "Alignment keeps the team moving forward.",
    priority: "progress",
    deadline: fiveDaysAgo,
    date: d5ISO,
    dueTime: "2:00 PM",
    timeRange: "2:00 PM \u2013 3:00 PM",
    estimatedDuration: 60,
    notes: "",
    subtasks: [],
    recurrence: "weekly",
    completed: true,
    order: 1,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "past-d5-3",
    title: "Workout session",
    whyItMatters: "Physical fitness directly impacts cognitive performance.",
    priority: "maintenance",
    deadline: fiveDaysAgo,
    date: d5ISO,
    dueTime: "6:00 PM",
    timeRange: "6:00 PM \u2013 7:00 PM",
    estimatedDuration: 60,
    notes: "",
    subtasks: [],
    recurrence: "daily",
    completed: false,
    order: 2,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    dailyCompletions: {},
  },
  // ─── Last Week ───────────────────────────────────
  {
    id: "past-d7-1",
    title: "Client presentation",
    whyItMatters: "Delivering results builds trust and opens new opportunities.",
    priority: "priority",
    deadline: lastWeek,
    date: d7ISO,
    dueTime: "10:00 AM",
    timeRange: "10:00 AM \u2013 11:30 AM",
    estimatedDuration: 90,
    notes: "Use the updated deck with Q2 numbers.",
    subtasks: [
      { id: "pd7-1", title: "Finalize slides", completed: true },
      { id: "pd7-2", title: "Practice delivery", completed: true },
      { id: "pd7-3", title: "Send follow-up email", completed: true },
    ],
    recurrence: "none",
    completed: true,
    order: 0,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "past-d7-2",
    title: "Vibecode session",
    whyItMatters: "Deep work sessions compound into major project progress.",
    priority: "progress",
    deadline: lastWeek,
    date: d7ISO,
    dueTime: "2:00 PM",
    timeRange: "2:00 PM \u2013 4:00 PM",
    estimatedDuration: 120,
    notes: "Focus on the new feature branch.",
    subtasks: [],
    recurrence: "none",
    completed: true,
    order: 1,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "past-d7-3",
    title: "Reflection",
    whyItMatters: "Weekly reflection keeps you aligned with long-term goals.",
    priority: "maintenance",
    deadline: lastWeek,
    date: d7ISO,
    dueTime: "8:00 PM",
    timeRange: "8:00 PM \u2013 8:30 PM",
    estimatedDuration: 30,
    notes: "Review the week's wins and areas to improve.",
    subtasks: [],
    recurrence: "none",
    completed: true,
    order: 2,
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  // ─── Next Monday (future) ────────────────────────
  {
    id: "future-mon-1",
    title: "Vibecode session",
    whyItMatters: "Deep work sessions compound into major project progress.",
    priority: "progress",
    deadline: displayDate(new Date(Date.now() + ((1 - new Date().getDay() + 7) % 7 || 7) * 86400000)),
    date: nextMondayISO(),
    dueTime: "2:00 PM",
    timeRange: "2:00 PM \u2013 4:00 PM",
    estimatedDuration: 120,
    notes: "Focus on the new feature branch.",
    subtasks: [],
    recurrence: "none",
    completed: false,
    order: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "future-mon-2",
    title: "Project planning",
    whyItMatters: "Planning prevents wasted effort.",
    priority: "priority",
    deadline: displayDate(new Date(Date.now() + ((1 - new Date().getDay() + 7) % 7 || 7) * 86400000)),
    date: nextMondayISO(),
    dueTime: "10:00 AM",
    timeRange: "10:00 AM \u2013 11:00 AM",
    estimatedDuration: 60,
    notes: "Review roadmap and assign tasks.",
    subtasks: [],
    recurrence: "none",
    completed: false,
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "future-mon-3",
    title: "Exercise",
    whyItMatters: "Physical fitness directly impacts cognitive performance.",
    priority: "maintenance",
    deadline: displayDate(new Date(Date.now() + ((1 - new Date().getDay() + 7) % 7 || 7) * 86400000)),
    date: nextMondayISO(),
    dueTime: "6:00 PM",
    timeRange: "6:00 PM \u2013 7:00 PM",
    estimatedDuration: 60,
    notes: "Full body workout.",
    subtasks: [],
    recurrence: "none",
    completed: false,
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "future-mon-4",
    title: "Weekly review",
    whyItMatters: "Weekly review keeps you aligned with long-term goals.",
    priority: "maintenance",
    deadline: displayDate(new Date(Date.now() + ((1 - new Date().getDay() + 7) % 7 || 7) * 86400000)),
    date: nextMondayISO(),
    dueTime: "8:00 PM",
    timeRange: "8:00 PM \u2013 8:30 PM",
    estimatedDuration: 30,
    notes: "Review the week's wins and areas to improve.",
    subtasks: [],
    recurrence: "none",
    completed: false,
    order: 3,
    createdAt: new Date().toISOString(),
  },
  // ─── Today ───────────────────────────────────────
  {
    id: "1",
    title: "Review Q2 strategy document",
    whyItMatters: "Strategic alignment drives every successful quarter.",
    priority: "priority",
    deadline: today,
    date: todayISO,
    dueTime: "9:00 AM",
    timeRange: "9:00 AM \u2013 11:00 AM",
    estimatedDuration: 120,
    notes: "Bring the competitive analysis from last week.",
    subtasks: [
      { id: "s1", title: "Read previous quarter review", completed: true },
      { id: "s2", title: "Analyze KPI trends", completed: true },
      { id: "s3", title: "Draft recommendations", completed: false },
      { id: "s4", title: "Prepare slides for board review", completed: false },
    ],
    recurrence: "none",
    completed: false,
    order: 2,
    createdAt: now,
  },
  {
    id: "2",
    title: "Call with design team",
    whyItMatters: "Design decisions shape the user experience for the next 6 months.",
    priority: "progress",
    deadline: today,
    date: todayISO,
    dueTime: "11:00 AM",
    timeRange: "11:00 AM \u2013 11:30 AM",
    estimatedDuration: 30,
    notes: "Join from the link in calendar invite.",
    subtasks: [
      { id: "s5", title: "Review latest mockups", completed: true },
      { id: "s6", title: "Prepare feedback notes", completed: false },
    ],
    recurrence: "weekly",
    completed: false,
    order: 3,
    createdAt: now,
  },
  {
    id: "3",
    title: "Morning journal entry",
    whyItMatters: "Journaling builds self-awareness and keeps you aligned with your values.",
    priority: "maintenance",
    deadline: today,
    date: todayISO,
    dueTime: "7:00 AM",
    timeRange: "7:00 AM \u2013 7:15 AM",
    estimatedDuration: 15,
    notes: "Write about what matters most today.",
    subtasks: [],
    recurrence: "daily",
    completed: true,
    order: 4,
    createdAt: now,
    dailyCompletions: { [todayISO]: true },
  },
  {
    id: "5",
    title: "Read 30 minutes",
    whyItMatters: "Reading compounds knowledge over time. 30 minutes daily = 50+ books per year.",
    priority: "maintenance",
    deadline: today,
    date: todayISO,
    dueTime: "9:00 PM",
    timeRange: "Anytime",
    estimatedDuration: 30,
    notes: "Currently reading: Atomic Habits by James Clear",
    subtasks: [],
    recurrence: "daily",
    completed: false,
    order: 6,
    createdAt: now,
    dailyCompletions: {},
  },
  {
    id: "6",
    title: "Workout session",
    whyItMatters: "Physical fitness directly impacts cognitive performance.",
    priority: "priority",
    deadline: today,
    date: todayISO,
    dueTime: "6:00 PM",
    timeRange: "6:00 PM \u2013 7:00 PM",
    estimatedDuration: 60,
    notes: "Focus on upper body today.",
    subtasks: [
      { id: "s10", title: "Warm up \u2013 10 min", completed: false },
      { id: "s11", title: "Strength training \u2013 30 min", completed: false },
      { id: "s12", title: "Cardio \u2013 15 min", completed: false },
      { id: "s13", title: "Cool down \u2013 5 min", completed: false },
    ],
    recurrence: "daily",
    completed: false,
    order: 7,
    createdAt: now,
    dailyCompletions: {},
  },
  {
    id: "8",
    title: "Evening reflection",
    whyItMatters: "Daily reflection accelerates personal growth and prevents burnout.",
    priority: "maintenance",
    deadline: today,
    date: todayISO,
    dueTime: "8:00 PM",
    timeRange: "8:00 PM \u2013 8:15 PM",
    estimatedDuration: 15,
    notes: "Write 3 things that went well and 1 thing to improve.",
    subtasks: [],
    recurrence: "daily",
    completed: false,
    order: 9,
    createdAt: now,
    dailyCompletions: {},
  },
  {
    id: "9",
    title: "Team standup",
    whyItMatters: "Quick daily syncs keep the team moving at full speed.",
    priority: "progress",
    deadline: today,
    date: todayISO,
    dueTime: "9:30 AM",
    timeRange: "9:30 AM \u2013 9:45 AM",
    estimatedDuration: 15,
    notes: "Keep it to 15 minutes max.",
    subtasks: [],
    recurrence: "daily",
    completed: true,
    order: 10,
    createdAt: now,
    dailyCompletions: { [todayISO]: true },
  },
  {
    id: "10",
    title: "Meditate for 10 minutes",
    whyItMatters: "Meditation rewires the brain for focus, calm, and resilience.",
    priority: "maintenance",
    deadline: today,
    date: todayISO,
    dueTime: "7:30 AM",
    timeRange: "7:30 AM \u2013 7:40 AM",
    estimatedDuration: 10,
    notes: "Use the Headspace app.",
    subtasks: [],
    recurrence: "daily",
    completed: true,
    order: 11,
    createdAt: now,
    dailyCompletions: { [todayISO]: true },
  },
  // ─── Tomorrow ────────────────────────────────────
  {
    id: "4",
    title: "Prepare presentation slides",
    whyItMatters: "Your ability to communicate ideas clearly accelerates team alignment.",
    priority: "priority",
    deadline: tomorrow,
    date: tomorrowISO,
    dueTime: "10:00 AM",
    timeRange: "10:00 AM \u2013 11:30 AM",
    estimatedDuration: 90,
    notes: "Use the new brand guidelines.",
    subtasks: [
      { id: "s7", title: "Outline key talking points", completed: false },
      { id: "s8", title: "Design slide templates", completed: false },
      { id: "s9", title: "Add data visualizations", completed: false },
    ],
    recurrence: "none",
    completed: false,
    order: 5,
    createdAt: now,
  },
  {
    id: "7",
    title: "Write project proposal",
    whyItMatters: "This proposal could unlock a $200K budget for the innovation lab.",
    priority: "priority",
    deadline: tomorrow,
    date: tomorrowISO,
    dueTime: "2:00 PM",
    timeRange: "2:00 PM \u2013 5:00 PM",
    estimatedDuration: 180,
    notes: "Review with finance team before submission.",
    subtasks: [
      { id: "s14", title: "Executive summary", completed: false },
      { id: "s15", title: "Market analysis", completed: false },
      { id: "s16", title: "Budget breakdown", completed: false },
      { id: "s17", title: "Risk assessment", completed: false },
    ],
    recurrence: "none",
    completed: false,
    order: 8,
    createdAt: now,
  },
  {
    id: "11",
    title: "Code review for feature branch",
    whyItMatters: "Good code reviews prevent bugs and spread best practices.",
    priority: "progress",
    deadline: tomorrow,
    date: tomorrowISO,
    dueTime: "3:00 PM",
    timeRange: "3:00 PM \u2013 3:45 PM",
    estimatedDuration: 45,
    notes: "Focus on the authentication module changes.",
    subtasks: [
      { id: "s18", title: "Review PR #234", completed: false },
      { id: "s19", title: "Review PR #235", completed: false },
    ],
    recurrence: "none",
    completed: false,
    order: 12,
    createdAt: now,
  },
  {
    id: "12",
    title: "Plan weekend trip",
    whyItMatters: "Rest and adventure fuel creativity and prevent burnout.",
    priority: "maintenance",
    deadline: "Friday",
    date: todayISO,
    dueTime: "Anytime",
    timeRange: "Anytime",
    estimatedDuration: 30,
    notes: "Look into the mountain cabin option.",
    subtasks: [
      { id: "s20", title: "Research destinations", completed: false },
      { id: "s21", title: "Book accommodation", completed: false },
      { id: "s22", title: "Plan activities", completed: false },
    ],
    recurrence: "none",
    completed: false,
    order: 13,
    createdAt: now,
  },
]
